### ISSUE TITLE
Upgrading to express 4

### ISSUE THREAD

**Issue by oscar-g** [brikteknologier/controller#30]
Not sure if people are still using this, but I started to [migrate to express 4](https://github.com/oscar-g/controller).  I've got the first block of tests passing with minor adjustments. One change is that `controller.app = express()` now equals: `express.Router()`.  So now when we actually use the controller routes in an Express app, we have to do `express.use(controller.app)`

[Express 4](https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x) executes middleware in the order they are added, which might impact how controller handles its 'middleware'.

Any thoughts?

**Comment by richarddavenport** [comment]
Any update on migrating to Express 4? I would really like to use Seraph with Seraph-Model and Seraph-Resource on top of Express 4.

**Comment by oscar-g** [comment]
@richarddavenport 
If you install express 3 and express 4 into your project, you can mount Controller (an instance of Express 3) into an express 4 route.  It's not the best solution, but its the easiest way to use Controller in an express 4 app.

**Comment by jonpacker** [comment]
As of now we have no plans to migrate to Express 4. It's sad, and I know it sucks, but it would require entirely rewriting this library, and we just don't have time for that right now. I might consider trying to hard-bake @oscar-g's solution into the library though, as a temporary solution.

**Comment by richarddavenport** [comment]
@oscar-g Not a bad idea actually, especially given the situation. Thanks guys! 
@jonpacker Anyway you might want some help rewriting Seraph? I might be able to help.

**Comment by jonpacker** [comment]
Finally found time to rewrite this, it should now be completely agnostic to which version of express you're using.

**Comment by jonpacker** [comment]
In the meantime `seraph-resource` is not updated yet, so that will need some work to be brought into compatibility with express 4 most likely. Will check soon.
